version: '3.8'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'uvg2024'
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "4200"  # Exponer el puerto 4200 internamente para ser utilizado por NGINX
    depends_on:
      - db
    networks:
      - app-network

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "4200:4200"  # NGINX manejará el puerto 4200 en lugar del frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge