version: '3.8'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'uvg2024'

  frontend:
    build: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - db

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    
