version: '3.8'

services:
  postgres:
    image: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: uvg2024

  angular:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"

