version: '3.8'

services:
  cifrados:
    image: cifrados
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: uvg2024

  frontend:
    image: frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app